export const ROUTERS = {
  HOME: '/',
  ABOUT: '/about',
  LIVING_ROOM: '/phong-khach',
  DINING_ROOM: '/phong-an',
  BED_ROOM: '/phong-ngu',
  WORK_ROOM: '/phong-lam-viec',
  KITCHEN_CABINETS: '/tu-bep',
  DECORATING_GOODS: '/hang-trang-tri',
  // PRODUCT_LIST: '/products',
  PRODUCT_DETAIL: '/product/:id',
  CART: '/cart',
  WISHLIST: '/wishlist',
  ADDRESS: '/account/address/',
  MY_ACCOUNT: '/account/profile/',
  CHANGE_PASSWORD: '/account/change-password/',
  MY_ORDER: '/account/orders/',
  CHECKOUT: '/checkout',
  ORDER_TRACKING: '/order-tracking',
  ERROR: '/404',
  ADMIN: '/admin',
  LOGIN: '/Login',
  REGISTER: '/Register',
}
