export const ROUTERS = {
  HOME: '/home',
  ABOUT: '/about',
  // LIVING_ROOM: '/phong-khach',
  // DINING_ROOM: '/phong-an',
  // BED_ROOM: '/phong-ngu',
  // WORK_ROOM: '/phong-lam-viec',
  // KITCHEN_CABINETS: '/tu-bep',
  // DECORATING_GOODS: '/hang-trang-tri',
  PRODUCT: '/home/:id/',
  PRODUCT_DETAIL: '/home/:id/:id/',
  // PRODUCT_DETAIL: '/product/:id',
  CART: '/home/cart/',
  WISHLIST: '/home/wishlist/',
  ADDRESS: '/home/address/',
  MY_ACCOUNT: '/home/profile/',
  CHANGE_PASSWORD: '/home/change-password/',
  MY_ORDER: '/home/my-orders/',
  CHECKOUT: '/home/checkout',
  ORDER_TRACKING: '/home/order-tracking/',
  ERROR: '/home/404/',
  ADMIN: '/home/admin/',
  LOGIN: '/home/Login/',
  REGISTER: '/home/Register/',
}
