export const ROUTERS = {
  HOME: '/',
  ABOUT: '/about',
  CUSTOMER_LOGIN: '/login-register',
  LIVING_ROOM: '/phong-khach',
  DINING_ROOM: '/phong-an',
  BED_ROOM: '/phong-ngu',
  WORK_ROOM: '/phong-lam-viec',
  KITCHEN_CABINETS: '/tu-bep',
  DECORATING_GOODS: '/hang-trang-tri',
  // PRODUCT_LIST: '/products',
  PRODUCT_DETAIL: '/product/:id',
  CART: '/cart',
  WISHLIST: '/wishlist',
  MY_ACCOUNT: '/my-account',
  CHECKOUT: '/checkout',
  ORDER_TRACKING: '/order-tracking',
  ERROR: '/404',
}
